version: '3'
services:
  flask-app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: coredna/coredna-chatbot:latest
    platform: linux/amd64
    container_name: flask-app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    expose:
      - "8000"
    networks:
      - coredna-network


  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app
    networks:
      - coredna-network

networks:
  coredna-network:
    driver: bridge
